const pages=[['home','⌂','Home'],['history','≡','History'],['dictionary','Aa','Dictionary'],['snippets','↗','Snippets'],['settings','⚙','Settings']];
let current='home',data={settings:{},stats:{},history:[],dictionary:[],snippets:[]},lastText='',loaded=false,latestMicLevel=0;
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
$('#nav').innerHTML=pages.map(([id,icon,name])=>`<button class="nav-button ${id==='home'?'active':''}" data-page="${id}"><span class="icon">${icon}</span>${name}</button>`).join('');
function section(title,subtitle){return `<div class="section-title"><h2>${title}</h2><p>${subtitle}</p></div>`}
function home(){const s=data.stats||{};return `<div class="hero"><span class="eyebrow">FAST · PRIVATE · EVERYWHERE</span><h2>Thought to text, without the friction.</h2><p>Select any text field, release the same two keys to begin, and repeat when your thought is complete.</p><div class="hotkey"><kbd>Ctrl</kbd><span>+</span><kbd>Windows</kbd></div><div class="mini-orb"></div></div>${data.pendingRecording?`<div class="card recovery"><h3>Recording saved after a failed dictation</h3><p class="muted">Retry transcription or delete the temporary recording.</p><button class="button primary" data-action="retryRecording">Retry transcription</button> <button class="button" data-action="discardRecording">Delete recording</button></div>`:''}<div class="card mic-card"><h3>Microphone activity</h3><div class="mic-meter" role="meter" aria-label="Microphone level" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><span></span></div><p class="muted" id="mic-help">Start dictation to check that ALTWISP hears your voice.</p></div><div class="metrics"><div class="metric"><span>WORDS DICTATED</span><b>${Number(s.words||0).toLocaleString()}</b></div><div class="metric"><span>RECORDINGS</span><b>${Number(s.dictations||0).toLocaleString()}</b></div><div class="metric"><span>WORDS / MIN</span><b>${s.seconds?Math.round(s.words*60/s.seconds):'—'}</b></div></div><div class="card"><div class="card-head"><div><h3>Your latest words</h3><p class="muted">Recovered here even when the target app changes.</p></div><button class="button" data-action="copy">Copy text</button></div><textarea id="latest" placeholder="Your next thought starts here.">${esc(lastText||(data.history?.[0]?.final_text||''))}</textarea></div>`}
function history(){return section('History','Every completed thought, searchable and easy to reuse.')+`<div class="card"><div class="card-head"><h3>Recent dictations</h3><button class="button" data-action="clearHistory">Clear history</button></div>${data.history?.length?`<table class="table"><thead><tr><th>WHEN</th><th>TRANSCRIPT</th><th>WORDS</th></tr></thead><tbody>${data.history.map(x=>`<tr><td>${new Date(x.created_at).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}</td><td>${esc(x.final_text)}</td><td>${esc(x.final_text.split(/\s+/).filter(Boolean).length)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Your finished dictations will appear here.</div>'}</div>`}
function entries(type){const dict=type==='dictionary',rows=data[type]||[];return section(dict?'Dictionary':'Snippets',dict?'Teach ALTWISP the words, names, and terms that matter to you.':'Turn short spoken triggers into complete reusable text.')+`<div class="card"><form id="entryForm" class="form-grid"><div class="field"><label>${dict?'SPOKEN PHRASE':'TRIGGER'}</label><input name="first" required placeholder="${dict?'alt wisp':'my sign off'}"></div><div class="field"><label>${dict?'REPLACEMENT':'EXPANSION'}</label><input name="second" required placeholder="${dict?'ALTWISP':'Thanks, have a lovely day.'}"></div><div></div><button class="button primary">Save ${dict?'word':'snippet'}</button></form></div><div class="card">${rows.length?`<table class="table"><tbody>${rows.map(x=>`<tr><td><b>${esc(dict?x.spoken:x.trigger)}</b></td><td>${esc(dict?x.replacement:x.expansion)}</td><td><button class="button" data-delete="${x.id}" data-table="${type}">Delete</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">Nothing here yet. Add your first entry above.</div>'}</div>`}
function settings(){const s=data.settings||{};return section('Settings','Tune accuracy, writing style, privacy, and startup behavior.')+`<div class="card"><div class="card-head"><div><h3>Transcription engine</h3><p class="muted">Local mode stays on-device after the model download.</p></div></div><form id="settingsForm"><div class="form-grid"><div class="field"><label>ENGINE</label><select name="transcription_backend"><option value="groq">Groq · fastest</option><option value="local">Local · private</option></select></div><div class="field"><label>LOCAL MODEL</label><select name="local_model">${['tiny','base','small','medium','large-v3'].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>LANGUAGE</label><input name="language" value="${esc(s.language||'auto')}"></div><div class="field"><label>WRITING STYLE</label><select name="style">${['neutral','casual','formal','concise'].map(x=>`<option>${x}</option>`).join('')}</select></div></div><div class="toggles" style="margin-top:18px"><label class="toggle"><span><b>AI polish</b><small> Clean punctuation and false starts</small></span><input type="checkbox" name="polish_enabled"></label><label class="toggle"><span><b>Save history</b><small> Keep completed transcripts locally</small></span><input type="checkbox" name="save_history"></label><label class="toggle"><span><b>Launch at sign in</b><small> Keep ALTWISP ready in the tray</small></span><input type="checkbox" name="launch_at_login"></label></div><div style="text-align:right;margin-top:16px"><button class="button primary">Save settings</button></div></form></div>`}
function render(){const meta={home:['PERSONAL DICTATION','Speak naturally.<br><em>Write beautifully.</em>','ALTWISP turns your voice into polished text wherever your cursor is.'],history:['YOUR WORDS','Your voice.<br><em>Remembered.</em>','Review and reuse every thought you chose to keep.'],dictionary:['PERSONAL LANGUAGE','It learns the way<br><em>you speak.</em>','Names, products, and terminology exactly as you write them.'],snippets:['VOICE SHORTCUTS','Say less.<br><em>Insert more.</em>','Reusable text expands from your own spoken triggers.'],settings:['YOUR WORKFLOW','Built around<br><em>your preferences.</em>','Control speed, privacy, tone, and startup behavior.']}[current];$('#eyebrow').textContent=meta[0];$('#title').innerHTML=meta[1];$('#subtitle').textContent=meta[2];$('#crumb').textContent=`Workspace / ${current[0].toUpperCase()+current.slice(1)}`;$('#page').innerHTML=current==='home'?home():current==='history'?history():current==='settings'?settings():entries(current);bind();}
function bind(){document.querySelectorAll('[data-action="copy"]').forEach(b=>b.onclick=()=>{navigator.clipboard.writeText($('#latest').value);toast('Copied','Transcript copied to your clipboard.')});const clear=$('[data-action="clearHistory"]');if(clear)clear.onclick=async()=>{if(confirm('Clear all saved transcript history?')){data=await window.altwisp.command('clearHistory');render()}};document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{data=await window.altwisp.command('deleteEntry',{table:b.dataset.table,id:Number(b.dataset.delete)});render()});const entry=$('#entryForm');if(entry)entry.onsubmit=async e=>{e.preventDefault();const f=new FormData(entry),dict=current==='dictionary';data=await window.altwisp.command(dict?'upsertDictionary':'upsertSnippet',dict?{spoken:f.get('first'),replacement:f.get('second')}:{trigger:f.get('first'),expansion:f.get('second')});render();toast('Saved',dict?'Dictionary updated.':'Snippet updated.')};const form=$('#settingsForm');if(form){const s=data.settings;for(const name of ['transcription_backend','local_model','language','style'])form.elements[name].value=s[name]??'';for(const name of ['polish_enabled','save_history','launch_at_login'])form.elements[name].checked=!!s[name];form.onsubmit=async e=>{e.preventDefault();const payload={transcription_backend:form.transcription_backend.value,local_model:form.local_model.value,language:form.language.value,style:form.style.value,polish_enabled:form.polish_enabled.checked,save_history:form.save_history.checked,launch_at_login:form.launch_at_login.checked};data=await window.altwisp.command('saveSettings',payload);toast('Settings saved','Your workflow is updated.')}}}
function bindExtras(){
  const meter=$('.mic-meter');
  if(meter){const amount=Math.round(latestMicLevel*100);meter.querySelector('span').style.width=`${amount}%`;meter.setAttribute('aria-valuenow',String(amount))}
  const retry=$('[data-action="retryRecording"]');
  if(retry)retry.onclick=async()=>{retry.disabled=true;try{await window.altwisp.command('retry');data.pendingRecording=false;render()}catch(error){retry.disabled=false;toast('Retry failed',error.message)}};
  const discard=$('[data-action="discardRecording"]');
  if(discard)discard.onclick=async()=>{data=await window.altwisp.command('discardRecording');render();toast('Recording deleted','The temporary audio file was removed.')};
  if(current==='settings'){
    $('#page').insertAdjacentHTML('beforeend','<div class="card"><h3>Microphone input</h3><p class="muted" id="activeMicrophone">Checking active microphone…</p><p class="muted">Choose a microphone and test it while speaking. Save it to use for dictation.</p><select id="inputDevice"><option value="">Windows default input</option></select> <button class="button" id="testMicrophone">Test selected microphone</button> <button class="button" id="saveMicrophone">Use this microphone</button><p class="muted" id="micTestResult" role="status"></p></div><div class="card"><h3>Updates</h3><p class="muted">Check GitHub for a newer ALTWISP release.</p><button class="button" id="checkUpdates">Check for updates</button> <button class="button" id="openReleases">Open releases</button><p class="muted" id="updateResult" role="status"></p></div>');
    const deviceSelect=$('#inputDevice'),micResult=$('#micTestResult');
    let microphoneList=[];
    const selectedMicrophone=()=>deviceSelect.value===''?null:Number(deviceSelect.value);
    const showActiveMicrophone=()=>{const id=data.settings.input_device??microphoneList.default;const device=microphoneList.devices?.find(item=>item.id===id);$('#activeMicrophone').textContent=device?`Active for dictation: ${device.name} (${device.hostapi})${data.settings.input_device==null?' · Windows default':''}`:'Active microphone unavailable. Choose another device.'};
    window.altwisp.command('listMicrophones').then(list=>{microphoneList=list;for(const device of list.devices){const option=document.createElement('option');option.value=String(device.id);option.textContent=`${device.name} (${device.hostapi})`;deviceSelect.append(option)}deviceSelect.value=data.settings.input_device==null?'':String(data.settings.input_device);if(deviceSelect.selectedIndex<0)micResult.textContent='Saved microphone is unavailable. Choose another device.';showActiveMicrophone()}).catch(error=>micResult.textContent=`Could not list microphones: ${error.message}`);
    $('#saveMicrophone').onclick=async()=>{try{data=await window.altwisp.command('saveSettings',{input_device:selectedMicrophone()});showActiveMicrophone();micResult.textContent='Microphone saved for dictation.'}catch(error){micResult.textContent=`Could not save microphone: ${error.message}`}};
    $('#testMicrophone').onclick=async()=>{micResult.textContent='Listening for two seconds… Speak now.';try{const reading=await window.altwisp.command('testMicrophone',{input_device:selectedMicrophone()});micResult.textContent=`${reading.device}: ${reading.level>.02?'Sound detected':'Very little sound detected'} (level ${Math.round(reading.level*100)}%). ${reading.level>.02?'Save this microphone to use it for dictation.':'Try another input device or check Windows microphone permissions and input volume.'}`}catch(error){micResult.textContent=`Microphone test failed: ${error.message}`}};
    $('#checkUpdates').onclick=async()=>{const result=$('#updateResult');result.textContent='Checking…';try{const update=await window.altwisp.command('checkForUpdates');result.textContent=update.available?`Version ${update.latest} is available. Open releases to install it.`:`You have the latest version (${update.current}).`}catch(error){result.textContent=`Could not check releases: ${error.message}`}};
    $('#openReleases').onclick=()=>window.altwisp.command('openReleases').catch(error=>toast('Could not open releases',error.message));
  }
}
const bindBase=bind;
bind=function(){bindBase();bindExtras()};
function toast(title,message){const t=$('#toast');t.querySelector('b').textContent=title;t.querySelector('span').textContent=message;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),4500)}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{current=b.dataset.page;document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x===b));render()});document.querySelectorAll('[data-window]').forEach(b=>b.onclick=()=>window.altwisp.window(b.dataset.window));$('[data-action="quit"]').onclick=()=>window.altwisp.window('quit');$('#toast button').onclick=()=>$('#toast').classList.remove('show');
function loadSnapshot(){window.altwisp.command('snapshot').then(x=>{data=x;loaded=true;render()}).catch(e=>toast('Worker unavailable',e.message))}
window.altwisp.onEvent(e=>{if(e.type==='state'){const s=$('#status');s.className=`status ${e.value}`;s.querySelector('b').textContent=e.value==='listening'?'Listening':e.value==='processing'?'Transcribing':e.value==='starting'?'Getting ready':'Ready';s.querySelector('small').textContent=e.message||'Ctrl + Windows to begin';if(!loaded)loadSnapshot()}if(e.type==='result'){lastText=e.text;loadSnapshot();toast(e.pasted?'Text inserted':'Text is ready',e.pasted?'Your words were placed in the selected field.':'The target changed; copy your text from Home.')}if(e.type==='error')toast(e.title,e.message)});
window.altwisp.onEvent(e=>{if(e.type==='volume'){latestMicLevel=Math.min(1,Math.max(0,Number(e.value)||0));const meter=$('.mic-meter');if(meter){const amount=Math.round(latestMicLevel*100);meter.querySelector('span').style.width=`${amount}%`;meter.setAttribute('aria-valuenow',String(amount))}}if(e.type==='state'&&e.value!=='listening'){latestMicLevel=0;const help=$('#mic-help');if(help)help.textContent=e.value==='processing'?'Recording stopped; transcribing…':'Start dictation to check that ALTWISP hears your voice.'}if(e.type==='state'&&e.value==='listening'){const help=$('#mic-help');if(help)help.textContent='Listening now. Speak to see the level move.'}if(e.type==='error'&&e.retry)loadSnapshot()});
loadSnapshot();render();
